### PR TITLE
refactor formatter and add mermaid support

### PR DESCRIPTION
**Pull request by loopingz**
I wanted to use mermaid classDiagram so I did an early implementation/refactoring of Formatter, which allow to keep former PlantUML but also to use Mermaid

I haven't yet added the unit test for mermaid format but would like some feedback before I do

### CODE REVIEW

**Comment by bafolts** [comment]
This looks great to me. Add unit tests and lets ship!

**Comment by loopingz** [comment]
The linter fail on GitHub Actions but not on my side:

```
no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
Warning: no-function-constructor-with-string-args rule is deprecated. Replace your usage with the TSLint function-constructor rule.
Warning: no-reserved-keywords rule is deprecated. Replace your usage with the TSLint variable-name rule.
Warning: no-increment-decrement rule is deprecated. Replace your usage with the TSLint increment-decrement rule.
Warning: no-unnecessary-bind rule is deprecated. Replace your usage with the TSLint unnecessary-bind rule.
```

This is this error on Github Actions

```
ERROR: /home/runner/work/tplant/tplant/src/Factories/ParameterFactory.ts:18:17 - This assertion is unnecessary since it does not change the type of the expression.
ERROR: /home/runner/work/tplant/tplant/src/Factories/PropertyFactory.ts:15:17 - This assertion is unnecessary since it does not change the type of the expression.
```

And without the cast tsc fails on my side.

Any ideas?

**Comment by bafolts** [comment]
If I remove my `node_modules` directory and run `npm run install` with the following change both `npm run build` and `npm run lint` pass for me on this branch.

```diff
diff --git a/src/Factories/ParameterFactory.ts b/src/Factories/ParameterFactory.ts
index 95a896c..4b41e2d 100644
--- a/src/Factories/ParameterFactory.ts
+++ b/src/Factories/ParameterFactory.ts
@@ -15,7 +15,7 @@ export namespace ParameterFactory {
         result.parameterType = checker.typeToString(
             checker.getTypeOfSymbolAtLocation(
                 parameterSymbol,
-                <ts.Declaration> parameterSymbol.valueDeclaration
+                parameterSymbol.valueDeclaration
             ),
             declaration
         );
```

**Comment by loopingz** [comment]
My VSCode is complaining but not the linter so all good with the latest change.
If you like/want I can refactor the test of PlantUML with the same type of result files test instead of the string[].join(os.EOL)

**Comment by loopingz** [comment]
If you are good with this one, I can create another PR with test refactoring if you want it.
The two other changes I'd like to work on is:
 - class target: so it draws a classDiagram with only parent and children classes
 - lerna monorepo compatibility

**Pull request merged**
