### PR TITLE
fix: add support for interfaces from namespaces

### LINKED ISSUE #83: Problem when interfaces are in a different namespace
tplant version: `3.1.1`

`Problem` when the interface is in a **different** namespace, when using in a class or in an interface, the svg is not generated. Below, the svg "content":
image

`Cause` I was able to replicate the problem with the code below:
```
namespace interfaces {
  export interface IGreeter {
    greet(): string;
  }
}

export class Greeter implements interfaces.IGreeter {
  greeting: string;
  prefix: string = "Hello, ";
  constructor(message: string) {
    this.greeting = message;
  }
  set prefix(prefix: string) {
    this.prefix = prefix;
  }
  greet(prefix: string = "Foo"): string;
  greet(): string {
    return this.prefix + this.greeting;
  }
}
```

### PR DESCRIPTION
**Pull request by bafolts**
Allows for interfaces with namespaces. This fixes #83

### CODE REVIEW

**Comment by bafolts** [comment]
This look good @rugoncalves?

**Comment by rugoncalves** [comment]
Thank you @bafolts!
Just tested, and:
1. in the example you have works!
2. if I move the namespace to another file **stops working**

`Example`
image

`Result`
image

**Comment by bafolts** [comment]
This error happens because you haven't referenced your namespace in the other file. You need to include it in `Greeter.ts`.

**Comment by rugoncalves** [comment]
Actually that was on purpose. In the context of the projects where I'm trying to use your (fantastic) tool, all the code is compiled to a single file - due to nuances of the low-code platform where it will be used - so we don't use imports.
Do see anyway to work around this nuance?

**Pull request merged**
